---
- name: Login to custom docker registry
  community.docker.docker_login:
    registry_url: '{{ custom_docker_registry.server_address }}'
    username: '{{ custom_docker_registry.username }}'
    password: '{{ custom_docker_registry.password }}'
  become: true
  become_user: '{{ item.key }}'
  loop: '{{ access.admin | dict2items }}'
  when: custom_docker_registry is defined

- name: Deploy Docker containers
  ansible.builtin.include_tasks: container.yml
  loop: '{{ docker_containers }}'
  loop_control:
    loop_var: container

- name: Setup cron jobs
  ansible.builtin.cron:
    name: '{{ item.name }}'
    job: '{{ item.job }}'
    minute: '{{ item.minute }}'
    hour: '{{ item.hour }}'
    user: 'root'
  become: true
  become_user: root
  loop: '{{ cron_jobs | default([]) }}'
