---
- name: Deploy Docker containers
  ansible.builtin.include_tasks: container.yml
  loop: '{{ docker_containers }}'
  loop_control:
    loop_var: container

- name: Setup cron jobs
  ansible.builtin.cron:
    name: '{{ item.name }}'
    job: '{{ item.job }}'
    minute: '{{ item.minute }}'
    hour: '{{ item.hour }}'
    user: 'root'
  become: true
  become_user: root
  loop: '{{ cron_jobs | default([]) }}'
