---
common_packages: # noqa var-naming[no-role-prefix]
  - ca-certificates
  - apt-transport-https
  - software-properties-common
  - build-essential
  - gnupg
  - gnupg-agent
  - mysql-client
  - acl
  - rsync
  - zip
  - unzip
  - curl
  - git
  - lsof
  - iputils-ping
  - dnsutils
  - iproute2
  - python3
  - python3-pip
  - python3.11-venv
  - jq

docker_packages: # noqa var-naming[no-role-prefix]
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
