---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true

- name: Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  become: true

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true
